### ISSUE TITLE
Test pilot icon's menu is blank, with "testpilot-addon:TypeError: can't convert undefined to object"

### ISSUE THREAD

**Issue by dholbert** [mozilla/testpilot#1048]
- [ ] Operating system: 64-bit Linux (Ubuntu 16.10)
- [ ] Firefox build: Nightly 50 (build id 20160706030233)

STR for me:
1. Click the test pilot add-on in my URL bar. (e.g. to deactivate some experiment)

ACTUAL RESULTS:
A blank menu appears. It never populates with any content. Additionally, this appears in my error console:

```
testpilot-addon:TypeError: can't convert undefined to object                  core.js:106
                Stack trace:
                [object Object]
```

**Comment by dholbert** [comment]
"core.js:106" ~~~seems to be in some error-handling code (which is tripping over itself when trying to report an earlier error, it seems):~~~  is just a line where testpilot is logging this error, not where the error actually occurred. It's this chunk of code:

```
// If error event and there are no handlers (explicit or catch-all)
// then print error message to the console.
if (count === 0 && type === 'error' && all === 0)
  console.exception(args[0]);
```

That last line is line 106.

**Comment by dholbert** [comment]
![browserconsole-screenshot](https://cloud.githubusercontent.com/assets/426803/16668367/7fa99638-4445-11e6-88b7-c126de5a3e11.png)

Here's a screenshot of the error in my browser console, in case it's helpful.
The "stack" chunk on the right is ellipsized because it's too long -- here's the copypasted text from that section:

```
stack:"getExperimentList@resource://gre/modules/commonjs/toolkit/loader.js -> resource://testpilot-addon/index.js:258:18
showExperimentList@resource://gre/modules/commonjs/toolkit/loader.js -> resource://testpilot-addon/index.js:236:27
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/panel.js:354:5
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
receive@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/utils.js:115:5
transform/next@resource://gre/modules/commonjs/toolkit/loader.js -> resource"
```

**Comment by dholbert** [comment]
Also worth noting: this worked correctly for me in the past. (i.e. this menu used to open usefully) Not sure when/why it stopped working.  I'm pretty sure I only have only test-pilot experiment activated -- activity center.

**Comment by dholbert** [comment]
I debugged a bit using browser toolbox. I placed a breakpoint in `showExperimentList`, and printed out `store` when it hit. That code is here:

```
function showExperimentList() {
  panel.port.emit('show', getExperimentList(store.availableExperiments,
                                            store.installedAddons));
}
```

In my main browsing profile (where this bug reproduces), `store` is:

```
Object {
  clientUUID: "07b12f7a-a370-40fd-bd58-9ae434262d87",
  lastTelemetryPingTimestamp: 1468388876915,
  telemetryPingPayload: Object,
  surveyChecks: Object }
```

In a fresh profile with a fresh Test Pilot install (where this bug does not reproduce), `store` is:

```
Object {
  surveyChecks: Object,
  clientUUID: "0c056dc2-db97-4c10-8c90-052376ac2a7b",
  metricsPrefsBackup: Object,
  lastTelemetryPingTimestamp: 1468441546173,
  telemetryPingPayload: Object,
  availableExperiments: Object,
  installedAddons: Object }
```

In particular, note that `availableExperiments` and `installedAddons` are not present in `store`, in my main profile. Those are the values that are queried in showExperimentList; and that's presumably how we're ending up with an exception about `undefined` here.

**Comment by dholbert** [comment]
OK, I think I've narrowed down the problem.

This "store" JS object (whose values are printed out above) seems to be backed by a file that lives in my profile directory, in ./jetpack/@testpilot-addon/simple-storage/store.json.  In my broken profile, that JSON file has these contents:

> {"surveyChecks":{"twoDaysSent":{},"oneWeekSent":{},"threeWeeksSent":{},"monthAndAHalfSent":{}},"clientUUID":"d7131aea-dcf9-4c5c-bc51-19c6bf6d7642","lastTelemetryPingTimestamp":1468443434772,"telemetryPingPayload":{"version":1,"tests":{}}}

Additionally, if I delete that JSON file and let it be regenerated, that's approximately what it ends up with again.

In a fresh profile with a fresh TestPilot install, that JSON file is much larger:

> {"surveyChecks":{"twoDaysSent":{},"oneWeekSent":{},"threeWeeksSent":{},"monthAndAHalfSent":{}},"clientUUID":"0c056dc2-db97-4c10-8c90-052376ac2a7b","metricsPrefsBackup":{"toolkit.telemetry.enabled":true,"datareporting.healthreport.uploadEnabled":true},"lastTelemetryPingTimestamp":1468441546173,"telemetryPingPayload":{"version":1,"tests":{}},"availableExperiments":{"@activity-streams":{"id":2,"url":"https://testpilot.firefox.com/api/experiments/2","title":"Activity Stream","short_title":"","slug":"activity-stream","thumbnail":"https://testpilot-prod.s3.amazonaws.com/experiments_experiment/e/1/e19739ea25188c866b654d3aa2616b27_thumbnail_1461817294_0590.png","description":"A rich visual history feed [...]

So the problem here seems to be that (a) my store.json file got deleted somehow, and (b) TestPilot is capable of recreating this file, but it recreates it without enough information to operate successfully (and in particular, it doesn't have enough information for Test Pilot to be able to open its menu without throwing an exception).

Also, I now have extremely-simple STR:
(1) Install Test Pilot, and try opening its menu. Notice that you see the list of available experiments.
(2) Quit Firefox.
(3) Delete ./jetpack/@testpilot-addon/simple-storage/store.json from your Firefox profile.
(4) Start Firefox, and click the Test Pilot menu.

ACTUAL RESULTS:  the menu is blank, and the browser console shows "TypeError: can't convert undefined to object" as noted above.

**Comment by dholbert** [comment]
@meandavejustice, looks like you [added this code](https://github.com/mozilla/testpilot/commit/98ae719a2c9ef12ed6e386e6563cd71bd764aaf9#diff-7562eb8eba3c3d86a671045f8c70107eR148). Any chance you could take a look here? See my STR in previous comment -- you should be able to reproduce locally if you just delete store.json.

**Comment by dholbert** [comment]
I'm guessing we must do some install-time setup to place a bunch of stuff in simple-storage, and then we never do that again, even if our simple-storage is missing/cleared/deleted. And unfortunately, the addon then trips over itself and throws an exception when trying to display the menu, in that scenario.

I'm guessing we need several things here:
 (1) If store.json disappears (i.e. if our simple storage is cleared), then the Test Pilot add-on should repopulate it (at startup or whatever) the same way that it does when the add-on is first installed. (getting experiment info from a server, etc)
 (2) The addon should perhaps be more tolerant of store.availableExperiments/store.installedAddons being undefined, in case of bad data. (It shouldn't throw an exception when those are undefined.)

Thing (1) is the most important thing here probably, but (2) would have helped here as well.

**Comment by meandavejustice** [comment]
@dholbert it looks like this was possibly fixed in https://github.com/mozilla/testpilot/commit/7738ed46ae7d96a29b724b11aec660e73a887952

**Comment by meandavejustice** [comment]
@dholbert Closing this as the fix has been deployed. Feel free to reopen if you continue seeing this issue.

**Comment by dholbert** [comment]
I'm still seeing the issue, though Test Pilot says it hasn't been updated since July 7th, so I think the problem is just that I haven't received the update.  (My version is reported as "0.7.2-tag-2016-07-05".)  The Add-ons pane "Check for Updates" feature doesn't give me any Test Pilot updates, either.

Are you sure the update has been deployed?

**Comment by pdehaan** [comment]
From IRC:

> dholbert> JSON_voorhees, could you reopen the issue, perhaps? (you suggested that I should if I could still reproduce, but GitHub doesn't seem to give me the ability to reopen it)

**Comment by dholbert** [comment]
I agree it looks like 7738ed4 should fix this, but it doesn't look like that has made it into a release yet.  If I directly view `resource://testpilot-addon/index.js` in Firefox, I see the old version of `showExperimentList` (without the added `|| {}`).

**Comment by meandavejustice** [comment]
This fix has been deployed.

verified by running:

```
curl -O -L http://testpilot.firefox.com/static/addon/addon.xpi
unzip addon.xpi
cat index.js | grep -i -C 2 "showExperimentList"
```

**Comment by dholbert** [comment]
Confirmed -- Test Pilot's menu is no longer blank.  At first, it wasn't quite back to normal, though now it is. In particular:
- When I clicked the Test Pilot button, its menu only had a single button, labeled "View all experiments."  (The menu did _not_ have a button for each experiment, like it used to.)
- When I click that, I got taken to a web page that let me enable/disable experiments. I disabled Activity Stream via that page's UI.
- After I'd disabled Activity Stream, I clicked the Test Pilot button on my toolbar again. This time, it had a fully-populated menu with a list of all 3 experiments (and the "view all" button).

So -- my previously-empty simple-storage must've been repopulated, either automatically (via some delay) or via one of my explicit actions (deactivating an experiment). Either way, this is back to normal.
