### ISSUE TITLE
Experiment details pages are missing Discourse links

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#1088]
It looks like we added a Discourse section in the sidebar per #1025

But looking at stage/prod, it doesn't look like any of the experiment details pages list the URLs, which makes the hanging header a bit awkward.

![firefox_test_pilot_-_activity_stream](https://cloud.githubusercontent.com/assets/557895/16931324/44c69418-4cf5-11e6-80c7-d7d2c4063c18.png)
**Figure 1:** Activity Stream.

---

![firefox_test_pilot_-_tab_center](https://cloud.githubusercontent.com/assets/557895/16931346/684877c6-4cf5-11e6-9fa1-d32ea30518be.png)
**Figure 2:** Tab Center

---

![firefox_test_pilot_-_universal_search](https://cloud.githubusercontent.com/assets/557895/16931366/7cbc3bf2-4cf5-11e6-9c1f-f336308e5db9.png)
**Figure 3:** Universal Search

**Comment by pdehaan** [comment]
Sorry, I guess this is maybe, possibly two semi-related bugs:
1. Somebody with prod admin access needs to enter the experiment specific Discourse links.
2. We shouldn't be displaying the "Discourse" label if we don't have a Discourse link in the database.

**Comment by johngruen** [comment]
Good spot @pdehaan

**Comment by johngruen** [comment]
fixed

**Comment by SoftVision-PaulOiegas** [comment]
Seems fixed on production but still missing on dev / staging. It would be nice to have the full pages content at least also on staging server for further deployment test runs.
