### ISSUE TITLE
no more 404 not working

### ISSUE THREAD

**Issue by karthik3195** [mozilla/testpilot#1269]
![firefox test pilot _no more 404s_](https://cloud.githubusercontent.com/assets/21154302/17836551/08862476-67b4-11e6-815f-4fcc1c3be476.png)
Thank you for contributing to Test Pilot!

Please use this form to report Test Pilot specific issues.

If you're experiencing a bug in Test Pilot, please include the following information:
- [ ] Operating system
- [x] Firefox build (Nightly, Developer Edition, Beta, Release)

---

If you think you've found an issue with one of the experiment add-ons, please file an issue in the appropriate repo below:
- Activity Stream:   https://github.com/mozilla/activity-stream/issues/new
- Tab Center:        https://github.com/bwinton/VerticalTabs/issues/new
- Universal Search:  https://github.com/mozilla/universal-search/issues/new

**Comment by pdehaan** [comment]
@karthik3195 Thanks for the bug report. Were you using Windows, macOS, or Linux?
Also, what Firefox channel were you using when you saw the error?

**Comment by karthik3195** [comment]
windows 10

**Comment by SoftVision-PaulOiegas** [comment]
I cannot reproduce this on Windows 10 x64 with Latest Firefox release 48.0.1 and latest Nightly 51.0a1 (production server). 
Even tried with low bandwidth since this errors were implemented for connection issues while downloading and enabling experiments. Tried with a simulated connection of 10 KB/s but except the fact that it took longer to install, no other issue observed. 

Maybe you had some connection issues while trying to install the experiment ? Can you still reproduce it ?

**Comment by gaby2300** [comment]
I still have the issue in today's nightly. Trying to install I get the
following message in the upper part of the site:

"Uh oh. ⁨No More 404s⁩ could not be enabled. Try again later."

Besides this, I still get the Firefox update warning. Thanks!

**Comment by dannycoates** [comment]
are you able to download it as a file?

https://testpilot.cdn.mozilla.net/nomore404s/wayback_machine-1.5.5-an%2Bfx.xpi

**Comment by gaby2300** [comment]
Yes! Thank
​s!​
Now I have to wait and see if it works. Do you have a URL to be able test
this by chance? Thanks again!

**Comment by ghost** [comment]
I think gaby2300's issue is being addressed in #1204 .  This issue may be related, but the original reporter hasn't replied so I'm going to close it. Thanks.

**Comment by gaby2300** [comment]
I am sorry but #1204 was a completely different issue. It had to do with a
connection problem due to my antivirus configuration. I changed it and the
problem was fixed.

I am afraid I am still seeing this issue in today's Nightly and Aurora
(Windows 7 64 bit), meaning I still see:

No More 404s requires Firefox 48 or later.
Make sure you're up to date.
https://support.mozilla.org/lt/kb/find-what-version-firefox-you-are-using
Considering I am using Nightly (Firefox 51) and Aurora (Firefox 50) I don't
really understand why I keep seeing this.

**Comment by SoftVision-PaulOiegas** [comment]
For now, that message is displayed no matter what browser version you have. We will probably correct it in the future, but for the moment it's expected behavior.

However, there were a bunch of issues with "fail to enable" specific experiments related to installed 3rd party software. 
1. The above one.
2. Unable to install Tab Center (http://goo.gl/0Bbt4Y) - issue appeared due to firewall setup that was blocking the add-on installation
3. Unable to install NoMore404s (Gaby's issue #1204) - again external problem due to antivirus.
4. Universal Search installation issue (#1202) - again seems to be something that could be related to 3rd party software since it's not reproducible on all environments.

In my opinion we have some **compatibility issues** here between our add-ons and other 3rd party software.  It seams that some of them **raise security issues and are blocked from installation**. Maybe we can do something to correct this from the add-ons ?
