### ISSUE TITLE
https://testpilot.firefox.com/undefined?undefined page opened after restarting Firefox after an update

### ISSUE THREAD

**Issue by marco-c** [mozilla/testpilot#1501]
A tab pointing to `https://testpilot.firefox.com/undefined?undefined` was opened after restarting Firefox Nightly after a Firefox update.

**Comment by past** [comment]
This just happened to me too.

**Comment by johannhof** [comment]
Happened to both me and my girlfriend. This might be happening to everyone :anguished:

**Comment by alexgibson** [comment]
I just hit this too (51.0a2)

```
"Download the React DevTools for a better development experience: https://fb.me/react-devtools"  vendor.f80539e20abf.js:8:3662
"Warning: It looks like you're using a minified copy of the development build of React. When deploying React apps to production, make sure to use the production build which skips development warnings and is faster. See https://fb.me/react-minification for more details."  vendor.f80539e20abf.js:1:15099
You are currently using minified code outside of NODE_ENV === 'production'. This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or DefinePlugin for webpack (http://stackoverflow.com/questions/30030031) to ensure you have the correct code for your production build.  vendor.f80539e20abf.js:13:7475
%c action @ 10:02:16.120 @@router/LOCATION_CHANGE  color: #000000;vendor.f80539e20abf.js:20
 prev state Object { routing: Object, experiments: Object, browser: Object, addon: Object }  vendor.f80539e20abf.js:20:775
 action Object { type: "@@router/LOCATION_CHANGE", payload: Object }  vendor.f80539e20abf.js:20:881
 next state Object { routing: Object, experiments: Object, browser: Object, addon: Object }  vendor.f80539e20abf.js:20:1075
%c action @ 10:02:16.182 setInstalled  color: #000000;vendor.f80539e20abf.js:20
 prev state Object { routing: Object, experiments: Object, browser: Object, addon: Object }  vendor.f80539e20abf.js:20:775
 action Object { type: "setInstalled", payload: Object }  vendor.f80539e20abf.js:20:881
 next state Object { routing: Object, experiments: Object, browser: Object, addon: Object }  vendor.f80539e20abf.js:20:1075
%c action @ 10:02:16.190 setHasAddon  color: #000000;vendor.f80539e20abf.js:20
 prev state Object { routing: Object, experiments: Object, browser: Object, addon: Object }  vendor.f80539e20abf.js:20:775
 action Object { type: "setHasAddon", payload: true }  vendor.f80539e20abf.js:20:881
 next state Object { routing: Object, experiments: Object, browser: Object, addon: Object }  vendor.f80539e20abf.js:20:1075
%c action @ 10:02:16.479 setClientUuid  color: #000000;vendor.f80539e20abf.js:20
 prev state Object { routing: Object, experiments: Object, browser: Object, addon: Object }  vendor.f80539e20abf.js:20:775
 action Object { type: "setClientUuid", payload: "75a95b07-8483-3141-93a1-f5975703848c" }  vendor.f80539e20abf.js:20:881
 next state Object { routing: Object, experiments: Object, browser: Object, addon: Object }  vendor.f80539e20abf.js:20:1075
%c action @ 10:02:16.484 setInstalled  color: #000000;vendor.f80539e20abf.js:20
 prev state Object { routing: Object, experiments: Object, browser: Object, addon: Object }  vendor.f80539e20abf.js:20:775
 action Object { type: "setInstalled", payload: Object }  vendor.f80539e20abf.js:20:881
 next state Object { routing: Object, experiments: Object, browser: Object, addon: Object }  vendor.f80539e20abf.js:20:1075
%c action @ 10:02:17.737 fetchExperiments  color: #000000;vendor.f80539e20abf.js:20
 prev state Object { routing: Object, experiments: Object, browser: Object, addon: Object }  vendor.f80539e20abf.js:20:775
 action Object { type: "fetchExperiments", payload: Object }  vendor.f80539e20abf.js:20:881
 next state Object { routing: Object, experiments: Object, browser: Object, addon: Object }
```

**Comment by johannhof** [comment]
@alexgibson I opened #1506 for the debug builds, I think/hope this is a separate issue :)

**Comment by SoftVision-PaulOiegas** [comment]
Got it too twice, but I'm not sure it's the update that generates this. At home this happened on 49.0.1 release and at work on Nightly. Also, just updated Nightly with today's build on a profile with Test Pilot already installed and didn't got the page again.

I'm gonna keep an eye on this and report back the steps to reproduce if I manage to find them.

**Comment by ianb** [comment]
I got this after a restart, no update involved.  I do have Tracking Protection installed.  [Page console](https://gist.github.com/ianb/0e29e18632f3630bd571bcbddf8784a3), but nothing too interesting, looks the same as the previously pasted console.

In the browser console:

`Blocking request: originTopHost:  testpilot.firefox.com  mainFrameOriginTopHost:  testpilot.firefox.com  requestTopHost:  www.google-analytics.com  requestHostInBlocklist:  true  background.bundle.js:299:7`

Looks like a CSP rule breaking GA, so presumably unrelated.

**Comment by ckprice** [comment]
Fixed in #1508.

**Comment by erikrose** [comment]
FWIW, I had the https://testpilot.firefox.com/undefined?undefined tab pop up while I was in the middle of reading Hacker News, days after I launched Firefox.

**Comment by chuckharmston** [comment]
#1508 was a good PR, but didn't fix this issue. ErikRose's comment got me to the real bug and fix, which is in #1517.
