### ISSUE TITLE
Test Pilot image is no longer displayed in Facebook or Twitter shared posts

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#1654]
[Affected versions]:
- Firefox 49.0.1 and up

[Affected Platforms]:
- All Windows

Prerequisites:
- Facebook or Twitter account already logged.

[Steps to reproduce]:
1. Open Firefox and navigate to "testpilot.firefox.com/share" page.
2. Click on the Facebook or Twitter share button.
3. Follow the process to share / tweet the Test Pilot page.
4. Navigate to Facebook or Twitter account page and observe the shared page.

[Expected result]:
- The shared posts correctly display the Test Pilot image.

[Actual result]:
- The shared posts have no Test Pilot image displayed.

[Notes]:
- Observed this on Twitter first but since last night, Facebook shared posts started also to show this issue.

![facebook share](https://cloud.githubusercontent.com/assets/17258026/19601655/e2c5aa02-97b2-11e6-82e2-5688bc81f09f.png)

**Comment by lmorchard** [comment]
Might have found the issue: https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Ftestpilot.firefox.com

```
Provided og:image URL, https://testpilot.firefox.com/static/images/thumbnail-facebok.png was not valid because it did not meet the minimum size constraint of 200px by 200px.
```

"facebok"

**Comment by SoftVision-PaulOiegas** [comment]
Nope, still not working on dev or stage for either Facebook or Twitter shares. Used a brand new profile so not a caching problem.

![no image in share](https://cloud.githubusercontent.com/assets/17258026/19639774/702c5fcc-99e2-11e6-83c8-2efcdb5df093.png)

**Comment by SoftVision-PaulOiegas** [comment]
In addition some network output.

![warning](https://cloud.githubusercontent.com/assets/17258026/19640168/31573c70-99e4-11e6-93b8-f6e7ef40c0f8.png)

and

![test pilot image maybe](https://cloud.githubusercontent.com/assets/17258026/19640173/36553a1a-99e4-11e6-9c75-c9f9ec836f44.png)

**Comment by ghost** [comment]
Fixed in https://github.com/mozilla/testpilot/pull/1659

**Comment by SoftVision-PaulOiegas** [comment]
Sorry guys, but still not working. Tested on all 3 servers using both Nightly and 49.0.2 release.

**Comment by chuckharmston** [comment]
I think this is because our `rel="canonical"` points to our production site, which still doesn't have the fixes yet. From [the debugging page](https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Ftestpilot.dev.mozaws.net) for our dev site:

<img width="716" alt="screen shot 2016-10-25 at 7 32 01 am" src="https://cloud.githubusercontent.com/assets/23885/19688039/29aea980-9a85-11e6-93d5-8e9373dc8f3e.png">

It's pretty clearly grabbing data from our production site, following a redirect to the canonical URL. Since this is in the HTML source on dev:

``` html
<meta property="og:image" content="https://testpilot.firefox.com/static/images/thumbnail-facebook.png" />
```

Rather than `thumbnail-facebok.png`, which is in prod, I'm comfortable calling this fixed and saying it's not testable until after the deployment today.

**Comment by chuckharmston** [comment]
(Although we should still validate that `thumbnail-facebook.png` is appropriately deployed on the dev site; @lmorchard?)

**Comment by lmorchard** [comment]
Yes, this is deployed to dev: https://testpilot.dev.mozaws.net/static/images/thumbnail-facebook.png

And also, yes - since this stuff has to use absolute links to production, we won't see a fix on Facebook until this stuff reaches production. We also use the canonical link to prod from all environments because we don't want to make it easy to share links pointing at our dev & stage environments.

**Comment by chuckharmston** [comment]
You can clear Facebook's cache from here: https://developers.facebook.com/tools/debug/sharing/

And Twitter's from here: https://cards-dev.twitter.com/validator

**Comment by SoftVision-PaulOiegas** [comment]
Great, we'll check it on prod after deploy then. Thanks for clarification !
