### ISSUE TITLE
Experiments pages are opened in same tab when using "Scroll click" or "Ctrl+click" shortcuts on cards

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#1795]
[Notes]:
- Open in a new tab functionality was added along with #1706 and correctly works from context menu, but not with peripherals shortcuts. 

[Affected versions]:
- Firefox 49.0.2 and up

[Affected Platforms]:
- All Windows
- All Mac

[Steps to reproduce]:
1. Open the browser and navigate to http://testpilot.dev.mozaws.net page.
2. Use Scroll wheel or old "Ctrl" key while clicking on an experiment card.
3. Observe the page behavior.

[Expected result]:
- The experiment details page is opened in a new tab.

[Actual result]:
- The experiment page is opened in the same tab.

[Additional notes]:
- Screen recording of the issue https://goo.gl/GD7zFN.

**Comment by smithfred** [comment]
I came across this issue today when visiting the Test Pilot website for the first time. How can a website *associated with a web browser* not get the absolute basics of web design right?

Don't break standard behaviour is pretty much rule number one of website design, doubly so if you specifically go out of your way to replace standard links with JS events/content loading etc.

/rant

Edit: adding the phrase "middle-click" here for issue discoverability.

**Comment by ckprice** [comment]
This should be fixed once #2351 has landed.

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue on dev server after #2351 landed and it seems that is still reproducible.

**Comment by fzzzy** [comment]
I have a fix for this now. Even though the experiment cards are actual &lt;a&gt; tags now, there was an onclick handler that was calling e.preventDefault. Removing this allows the normal anchor behavior to work.

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue and is no longer reproducible on dev server. Marking as verified.
