### ISSUE TITLE
https://testpilot.firefox.com/ does not load using Firefox Focus for iOS

### ISSUE THREAD

**Issue by alexgibson** [mozilla/testpilot#2298]
iOS 10.2.1, Firefox Focus 3.1
----------------------------

Site does not load, blank screen:

![img_3683](https://cloud.githubusercontent.com/assets/400117/23751184/165d0cf2-04c8-11e7-8dcf-c9f9a779335a.PNG)

iOS 10.2.1, Safari
-----------------

Site loads as expected:

![img_3684](https://cloud.githubusercontent.com/assets/400117/23751188/1bf4ca24-04c8-11e7-83e7-2d8de15e163e.PNG)

**Comment by SoftVision-CosminMuntean** [comment]
I have manged to reproduce this issue on iOS 10.2.1 using Firefox Focus 3.1..
After further investigations I have noticed on iOS that even in Firefox, Safari and Chrome the Test Pilot page is not loaded in Private Mode. 

I have also tested this on Android (6.0.1) and it seems that the Test Pilot page is successfully loaded in Firefox and Chrome using Private Mode.

**Comment by ghost** [comment]
Can you try this on https://testpilot.dev.mozaws.net/ ?  I suspect this is fixed by that patch danny landed to unblock on telemetry

**Comment by alexgibson** [comment]
Sadly it seems https://testpilot.dev.mozaws.net/ is still broken using Focus.

**Comment by fzzzy** [comment]
I have verified that this still happens, even though we made some big changes recently that might have helped. Does anyone have any suggestions on how to debug this? I can't find any way to see a web console or a list of errors.

**Comment by johngruen** [comment]
Seems like this would be an easy fix. Like we should not block on async requests

**Comment by johngruen** [comment]
@fzzzy do you have a sense of why this is happening. I am trying to put together #2563 and trying to figure out the difficulty here.

**Comment by fzzzy** [comment]
@johngruen Just a guess, but if focus is blocking some requests maybe that could cause it. Is it still happening?

**Comment by chuckharmston** [comment]
Could always use Wireshark to compare the expected set of requests with the actual ones that happen?

**Comment by fzzzy** [comment]
I just tested with Focus against prod, and it works fine. My guess is that focus was blocking the user counts request, and the page never finished loading. We removed the user counts a few sprints back.

**Comment by johngruen** [comment]
only Focus for iOS is affected.

**Comment by chuckharmston** [comment]
I can't repro on release or beta on iOS.

**Comment by fzzzy** [comment]
@johngruen Yes, I tested with Focus for iOS...

**Comment by alexgibson** [comment]
I can confirm using the latest version of Focus on iOS that the site now loads OK for me too.
