### ISSUE TITLE
Voice Fill and Notes are wrongly enabled on unsupported Fx version when installed together with Test Pilot add-on

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2848]
**[Notes]:**
**- I would suggest that we should remove entirely the top part with "Install Test Pilot & Enable <experiment_name>" when the experiment is unsupported on a Firefox older version.**
- Also, this is related to #2109, where we originally requested that error messages should be displayed even if TxP add-on is not installed.
- This scenario is very easily encountered by all ESR users for example.

**[Affected versions]:**
- Firefox 53.0.3 and older

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- The "testpilot.env" string type pref was manually added in "about:config" page with "dev" value.
- The "extensions.webapi.testing" boolean type pref was manually added in "about:config" page with "true" value.
- Old Firefox 53.0.3 or lower was installed / extracted on the system. 

**[Steps to reproduce]:**
1. Open the old browser version with the profile from prerequisite and navigate to https://testpilot.dev.mozaws.net/experiments page.
2. Click on the "Voice Fill" or "Notes" experiment card.
3. Click on "Install Test Pilot & Enable <experiment_name>" button.
4. Observe the page behavior.

**[Expected result]:**
- Test Pilot add-on is successfully installed, but Voice Fill or Notes experiments are not since they require at least Firefox 54 to properly work. 

**[Actual results]:**
- Test Pilot add-on is successfully installed but also Voice Fill or Notes experiments are wrongly installed together with it.

**[Additional Notes]:**
- Here is a screen recording of the issue: https://goo.gl/9uZRKg.

**Comment by ghost** [comment]
We think this is fixed with the deploy going out tomorrow.  Other issue is #2731

**Comment by SoftVision-PaulOiegas** [comment]
@wresuolc this is still reproducing on stage server and now the dev server add-on is not installing so I cannot confirm this is fixed or not.
The #2731 issue was indeed fixed but that covers only the part when Test Pilot add-on is already installed. In this issue we are talking about installing together the TxP add-on with Voice Fill or Notes add-ons.

I'll recheck this when we have a functional server. Right now both dev and stage are either broken or outdated...

**Comment by SoftVision-PaulOiegas** [comment]
Re-verified the issue and seems to be fixed on both dev and stage servers despite of version difference between servers.

**Comment by SoftVision-PaulOiegas** [comment]
My mistake, I thought this was another bug that I needed to verify. 
This one still reproduces even after the changes for #2731 have been merged. Verified this with the build on stage, since the dev one cannot be installed on FX 52 or 53 even with all the 5 prefs set.

**Comment by chuckharmston** [comment]
Old versions now get a message preventing them from viewing the site at all. Closing.

**Comment by SoftVision-PaulOiegas** [comment]
@chuckharmston Nope, still reproducing for Notes at least. They raised the min version to Fx 57, but Test Pilot still having 54 as min version. We have a [bug](https://github.com/mozilla/testpilot/issues/3328) for this since Feb 6th, but no one worked on it since then...

You can see in the screenshot that I've enabled it, but the toolbar button is a placeholder and Notes sidebar is totally broken... So, until the above change request is implemented, this is a perfectly valid issue.

![image](https://user-images.githubusercontent.com/17258026/37028403-d3051a3e-213c-11e8-943c-1fa3a3d3a26e.png)

**Comment by SoftVision-PaulOiegas** [comment]
This is no longer reproducible due to the `min_version 58` change for Test Pilot add-on implementation. 

However, this is just an issue masking and it's not treating the root cause. If we'll have a newer experiment that will require Fx 59 to work, this issue will be again reproducible. Unless, we will be raising the `min_version` after each new Fx release.
