### ISSUE TITLE
Test Pilot no longer works on dev server

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#3005]
[Affected versions]:
- Firefox 56.0 and above

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = stage" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites and navigate to https://testpilot.dev.mozaws.net page.
2. Observe the Test Pilot page.

[Expected result]:
- Test Pilot page is successfully loaded and works as expected.

[Actual result]:
- Only the blue background with stars and constellations is loaded.

**Comment by fzzzy** [comment]
And absolutely no error messages anywhere...

**Comment by fzzzy** [comment]
The head of master works fine when testing locally, so there must be a deploy problem.

**Comment by fzzzy** [comment]
app.js is 404.

**Comment by fzzzy** [comment]
I fixed it by retriggering the build from the latest commit on master:

https://circleci.com/gh/mozilla/testpilot/6075

**Comment by lmorchard** [comment]
Grr. Don't know why this is still happening. Seemed like an issue of parallel deploys pushing an index.html that had the wrong path to the app.345345345.js that ended up on S3, but [I thought I fixed that](https://github.com/mozilla/testpilot/commits/master/circle.yml) between serializing deploys and waiting for Cloudfront invalidations

**Comment by SoftVision-CosminMuntean** [comment]
It seems that this issue is again reproducible. If you navigate to "testpilot.dev.mozaws.net", only the blue background with stars and constellations is loaded.
But, if you navigate to "testpilot.dev.mozaws.net/experiments" or other Test Pilot pages, the pages are correctly loaded.

**Comment by lmorchard** [comment]
Seems like it's working again, after a CircleCI rebuild
