### ISSUE TITLE
[Featured Experiment] The "Enable Notes" button remains in hovered state if enable process is canceled

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3316]
**[Affected versions]:**
- Firefox v58.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".
- Test Pilot add-on was already installed on the same profile.

**[Steps to reproduce]:**
1. Open Firefox browser with the profile from prerequisites and navigate to https://testpilot.dev.mozaws.net/experiments page.
2. Click the "Enable Notes" green button from "Featured Experiment" area.
3. Click the "Cancel" button on the displayed doorhanger for the Notes experiment enable.
4. Observe the green button behavior.

**[Expected result]:**
- The button passes from "Enabling..." animation state back into "Enable Notes" default state of the button.

**[Actual result]:**
- The button passes from "Enabling..." animation state back into "Enable Notes" state, but in the hovered state not default one.

**[Notes]**
- Clicking outside the button returns it to default state.
- This issue does not occur on Mac OS.
- The issue also occurs on stage server.
- Here is a screen recording of the issue: https://goo.gl/LNbG5k.

**Comment by chuckharmston** [comment]
That's the :focus state, which happens to be the same as the :hover state. It's a UX call if they should be different.

**Comment by dominictwlee** [comment]
I'll give this a go if no one else is working on it.

**Comment by SoftVision-PaulOiegas** [comment]
@dominictwlee of course, you can have it!. 👍 However, please take into consideration that this button is displayed in a section that is temporarily hidden right now. In order to have it displayed, you need to edit, for example, the `notes.yaml` file at the `featured` code line from `no` to `yes`.

**Comment by dominictwlee** [comment]
This is more challenging for me than I initially anticipated. I assume that the focus state should be kept in the CSS files for keyboard accessibility so I won't mess with that.

This leads me to think that I have to tinker with the MainInstallButton component, perhaps modifying the styles towards the end of the "install" function 
![screenshot from 2018-05-03 12-13-33](https://user-images.githubusercontent.com/34794189/39573516-736dfe08-4ecb-11e8-9af5-7a18245f3215.png)


Am I heading in the right direction or am I completely off? Thanks!

**Comment by SoftVision-PaulOiegas** [comment]
@dannycoates @meandavejustice ^

**Comment by dannycoates** [comment]
I can't reproduce this on master anymore. I think it was fixed in #3440

**Comment by SoftVision-PaulOiegas** [comment]
@dannycoates still reproduces on Windows and Linux as mentioned in comment 0, while it works on MacOS. We're you checking on MacOS?

However, it seems that most of the website buttons are showing the same behavior on Windows and Linux. ("Install", "Enable/Disable", "Get Started", "Sign Up Now", etc). Maybe I should adapt this one as a general issue to fix all of them at once?
