### ISSUE TITLE
The "Launch Tour" string is wrongly displayed in lowercase characters on French [fr-fr]

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/testpilot#3591]
**[Affected versions]:**
- Nightly 62.0a1

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".
- Add French [fr-fr] as top language for web content from "Options > General > Language" section.

**[Steps to reproduce]:**
1. Open Firefox browser with the profile from prerequisites and navigate to https://testpilot.dev.mozaws.net page.
2. Scroll down on the Homepage and click on one of the active experiments cards.
3. Observe the "Launch Tour" (Visite guidée) string localization under the experiment logo.

**[Expected result]:**
- The string has the first word starting with capital letter. 

**[Actual result]:**
- The string starts with lowercase letter.

**[Notes]:**
- Attached a screenshot with the behavior:
![lowercase string](https://user-images.githubusercontent.com/31244235/40721725-11c53dfc-6423-11e8-9c8e-88c7ebc532e7.png)

**Comment by flodolo** [comment]
cc @TheoChevalier 

Looks like this one is used in only [one place](https://github.com/mozilla/testpilot/blob/964b6239617519c75d58ac02a044f1ba749e579d/frontend/src/app/containers/ExperimentPage/DetailsOverview.js#L127)

**Comment by TheoChevalier** [comment]
Thanks, just fixed in Pontoon https://pontoon.mozilla.org/fr/test-pilot-website/all-resources/?search=Launch+tour&string=159289

**Comment by ghost** [comment]
thanks

**Comment by Softvision-CristinaBadescu** [comment]
This issue is still reproducible on Test Pilot, dev server. Just to be sure, considering [this comment](https://github.com/mozilla/testpilot/issues/3596#issuecomment-395133509), the issue is going to be fixed only next week. Is that right? If yes, I'll retest it then.

**Comment by flodolo** [comment]
It might be available earlier on the dev server, but it requires a merge from l10n to master branch.

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible on latest Nightly build 62.0a1, on Test Pilot, dev server. Verified on Windows 10 x64, Mac 10.13.5 and Arch Linux 4.12.
