### ISSUE TITLE
Signing up with a non-Mozilla email redirects you to a 404 page

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#487]
Found in 61d380e282e3263b84bdd485b43999804262b40d (via https://testpilot.stage.mozaws.net/__version__)

``` json
{
    "version": "2016-03-14",
    "source": "https://github.com/mozilla/testpilot",
    "commit": "61d380e282e3263b84bdd485b43999804262b40d"
}
```

---

If you try signing up to Test Pilot with a non @mozilla.com email address, it takes you to a 404 page.

I just lost my sweet, sweet bug report, and now I'm stuck in a flow where I'm registered as my @mozilla.com account, but it won't let me fully install the add-on or sign out, so I can't get back and take a screenshot, so you're stuck with this hot garbage bug report.

Actually, I can verify on prod... After using my personal email address to sign in, I'm ultimately redirected to https://testpilot.firefox.com/accounts/inactive/ which 404s with a Choppy barrel-type roll.

![firefox_test_pilot](https://cloud.githubusercontent.com/assets/557895/13794062/451ef2c0-eab7-11e5-8e53-dd8f47e6f579.png)

**Comment by pdehaan** [comment]
Ref: #391 #449

**Comment by lmorchard** [comment]
Ah, yup, looks like [this page was removed](https://github.com/mozilla/testpilot/pull/472/files#diff-0e22a4ebd3b1cb538012dbfeb33ca468L6) in #472 with the UI change from old Idea Town to Test Pilot... but the backend still redirects inactive users to that, expecting the coming-soon page to be there.

@johngruen - can we get that account-inactive-page / coming soon page back? Seems like it's part of the issue in #508

**Comment by clouserw** [comment]
From triage meeting:  the plan for #508 will trump this one.  Is there a :trump: ?

**Comment by chuckharmston** [comment]
Yes. ![trump](https://cloud.githubusercontent.com/assets/23885/14028300/6d77c876-f1c1-11e5-9fa9-a83b6dcda017.png)

**Comment by lmorchard** [comment]
I think this issue still requires action: As long as we have the mozilla.com email restriction, the backend still redirects inactive users to `/accounts/inactive`. So, we need a page of _some kind_ there - even if it's "coming soon".  Otherwise, we still get the 404s this issue was opened to report.

That, or we need to remove the "invite-mode" code from the backend and figure out what else to do - e.g. stop accepting registrations & creating inactive accounts at all from non-whitelisted email domains.

**Comment by lmorchard** [comment]
Though, FWIW, this becomes a moot point when we launch fully and set `ACCOUNT_INVITE_ONLY_MODE` to `False` - because that disables the email restriction and redirect code.

**Comment by pdehaan** [comment]
I believe this is fixed in latest master. Closing.

**Comment by lmorchard** [comment]
Technically, the problem is still there, but we changed `ACCOUNT_INVITE_ONLY_MODE` to `False` in deployment and that switches off the email address restriction. Eventually #687 will make this go away for good.
