### ISSUE TITLE
Weird unicode text on page title

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#875]
Visiting experiment detail pages show weird characters in the title bar.  Screenshot @ https://www.evernote.com/shard/s3/sh/bf3f2560-af38-42e2-ae87-83246ca9c3e7/ee84a96f17b0ae021559351109aabd56

This is in Nightly on Linux, although I think Nick runs windows.  The original report is https://github.com/bwinton/VerticalTabs/issues/144

**Comment by ghost** [comment]
Experiment names are no longer in the titles, so, I guess this is fixed-ish

**Comment by ghost** [comment]
Experiment titles are back now and so is this bug...

**Comment by mathieuinottawa** [comment]
Looks different to me, but still not right:

![odd chars](https://cloud.githubusercontent.com/assets/26018083/23327885/51154d72-fae2-11e6-96f0-d38c41293b39.png)

**Comment by ScottDowne** [comment]
I noticed while the page is loading, it's fine. Then it hits `setPageTitleL10N` https://github.com/mozilla/testpilot/blob/master/frontend/src/app/containers/ExperimentPage.js#L214 and it updates the title, creating the issue. I think.

So maybe this is being caused by whatever is doing l10n?

**Comment by ScottDowne** [comment]
I think this and #1828 are related.

If you go here: https://github.com/l20n/l20n.js/blob/master/docs/html.md

At the bottom it says "If you care about IE11 you'll need the HTMLTemplateElement polyfill. L20n.js uses HTMLTemplateElements (<template>) to safely set contents of DOM nodes."

So maybe the weird characters are the broken template elements? They offer a solution which  havn't looked into yet.

**Comment by ghost** [comment]
Yeah, interesting, although I can reproduce the page title ones in Firefox.  /cc @stasm for the potential for an l20n tie-in

**Comment by ScottDowne** [comment]
Yeah, I think it's very likely l20n.js related, but I'm less sure it's `<template>` related.

I tried a few browser/OS combinations until I found one that failed (Windows + IE 11), I didn't find a FF that failed. I'm on Fedora (stable + nightly), and I also tried WIndows (stable and beta FF).

However, I also tried a template polyfil, and it didn't fix it.

I think a reduced test case to confirm this is in l20n.js and not something in test-pilot, would probably be the next thing I try.

**Comment by stasm** [comment]
L20n (and Fluent) use Unicode's FSI and PDI marks to isolate the direction of interpolated text. This is useful when the text around an interpolation has a different direction than the text inside of the interpolation. The bidi algorithm needs a bit of help to properly render punctuation marks in those cases.

Unfortunately, FSI and PDI don't render well on Windows on some browsers. Is this issue only reproducible on IE11? Do you know if Edge is affected?

It might be best to turn off this behavior in l20n.js for browsers that are known to not support FSI and PDI well.

**Comment by ScottDowne** [comment]
@stasm Yeah, Edge is fine.

**Comment by stasm** [comment]
Thanks for the information. I filed https://github.com/l20n/l20n.js/pull/178. I'll be able to test it on Thursday.

**Comment by ghost** [comment]
I'm still reproducing this in Firefox Nightly on Ubuntu (and have been able since at least when this was filed).  No one else sees this in Nightly's title bar (screenshot in first comment)?

Edit:  The original screenshot was from Nick, not me.  So, attaching what I see today:  
![nightly](https://cloud.githubusercontent.com/assets/16946141/25634068/248324ac-2f2e-11e7-8a3f-9805b95a2630.png)

**Comment by ScottDowne** [comment]
@wresuolc Yeah, it's fine for me on Fedora + nightly.

I'll see if I can wrangle a way to test on Ubuntu.

**Comment by ScottDowne** [comment]
I tested firefox and nightly on Ubuntu, and it didn't see this issue :(

I also tested https://github.com/l20n/l20n.js/pull/178 best I could and could see a difference in IE 11.

**Comment by meandavejustice** [comment]
Ubuntu, xmobar/xmonad, Firefox 54.0a2

Same behavior as @ScottDowne describes above. Title is fine until page is finished loading, then it changes.

![weird-unicode-title](https://cloud.githubusercontent.com/assets/1844554/26366565/8e6c16e4-3fb9-11e7-8b97-12df96806d6d.png)

**Comment by ScottDowne** [comment]
Ah yes, interesting, for Linux it's probably more related to the status bar/desktop manager than the browser itself.

**Comment by johngruen** [comment]
ref #1714

**Comment by meandavejustice** [comment]
This appears to be fixed now, probably in #1714 woohoo!

![whatever](https://user-images.githubusercontent.com/1844554/33782283-16a9a54a-dc26-11e7-9520-290906dad6a4.png)

**Comment by SoftVision-PaulOiegas** [comment]
@meandavejustice This still occurs on experiments details page on Windows 10 Edge browser.
![image](https://user-images.githubusercontent.com/17258026/33827075-b5dd1e76-de6f-11e7-9238-de7b293890b0.png)
