### ISSUE TITLE
Console error: `sync-installed failed undefined` on /experiments

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#960]
OSX, updated Nightly.

STR:
- Have Activity Stream installed.
- Refresh homepage.
- Click on the Firefox Test Pilot link in the header/logo.
- Keep clicking until you see that the homepage has loaded without the active checkbox appearing on Activity Stream (takes < 5 or so tries).

Expected Result:
- There should be a green checkmark next to the Activity Stream area.

Actual Result:
- Console error ([full text](https://pastebin.mozilla.org/8875910)), and no checkmark.

![image 2016-06-08 at 1 55 28 pm](https://cloud.githubusercontent.com/assets/8632184/15910890/eb67fcd2-2d81-11e6-9d8c-b936ac612504.png)

And a quick note that whenever this happens, if I click into the experiment details page (e.g. `/experiments/activity-stream`), I get a blank screen.

![image 2016-06-08 at 1 49 10 pm](https://cloud.githubusercontent.com/assets/8632184/15911100/06970e3e-2d83-11e6-8ee6-652aa69ce8f4.png)

**Comment by ckprice** [comment]
Fixed in #965.

**Comment by meandavejustice** [comment]
@ckprice We are still getting these errors occasionally, #965 doesn't address this issue, just another failure point that was exposed by this issue. Reopening

**Comment by iSimonWeb** [comment]
:+1: I've been experiencing this issue too.
Actually I still haven't tried any experiment due to this bug.

**Comment by lmorchard** [comment]
I think PR #1054 will fix this on the next deployment - because [it removes the experiment status sync code altogether](https://github.com/mozilla/testpilot/pull/1054/files#diff-e3b6f01f644924c95a8f76002ac5ab85L41).

**Comment by lmorchard** [comment]
This _should_ be fixed on stage, going to close this but we can reopen if it resurfaces
